DROP TABLE IF EXISTS recipe;
DROP TABLE IF EXISTS shopping_list;
DROP TABLE IF EXISTS users;

CREATE TABLE recipe(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image text,
    name text,
    ingredients text [],
    directions text [],
    servings int,
    cook_time text,
    classification text,
    description text
);

CREATE TABLE shopping_list(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id int,
    ingredients text [],
    quantity text []
);

CREATE TABLE users(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text,
    password text,
    first_name text,
    last_name text,
    email text,
    servings int
);